### ISSUE TITLE
Issue on creating container

### ISSUE THREAD

**Issue by zenonVR** [elgarf/vMixUTC#1]
Hi,

Thanks for Project , I'm looking to work a bit as test with it and see how far i can go and use it...
actually I saw as issue:
I have compiled the version from 01.02.2018. The last one you have as source is not working because your Regex checking the Vmix sent packet has an issue, so no command are sent to Vmix at all.
another Bug by creating a container you have an exception an prog is crashing:
Log attached
[2018-02-09.log](https://github.com/elgarf/vMixUTC/files/1711678/2018-02-09.log)

And a final point, Can you add in the list of sport for the score "Rugby" with point list (+2,+3,+5) would be great.. 

Thanks a lot

**Comment by zenonVR** [comment]
in version from 28.03.2017 , container are working

**Comment by elgarf** [comment]
Which controls do you pack into container? Can you share your vmc file?

**Comment by elgarf** [comment]
It should be fixed now. Please, check.

**Comment by zenonVR** [comment]
did you fix also the Pb with the Regex testing the validity url sent to Vmix ?
I will compile and see how it's working with the container

**Comment by elgarf** [comment]
I've fixed non working buttons (looks like regex was only for url, without parameters).

**Comment by zenonVR** [comment]
seems to be ok, with button send, container and new sport Rugby ;)
Thx a lot
