### ISSUE TITLE
usage vMixUTCNDIMonitorDataProvider

### ISSUE THREAD

**Issue by zenonVR** [elgarf/vMixUTC#2]
hi,

here also after few seconds the UTC crashed due to a memery overun in the version from 01.02.2018

Thanks for the job

**Comment by elgarf** [comment]
Check new version, please.

**Comment by zenonVR** [comment]
Hi, 
Thanks for new releases, it takes a bit longer but crashed also.
[2018-02-12.log](https://github.com/elgarf/vMixUTC/files/1715656/2018-02-12.log)

BTY I put an other comment but closed it by mistake.
I'll reopen it so you can see the other pb with the communication with  Vmix

**Comment by elgarf** [comment]
Can you say how much memory it eats?
What OS do you use?

**Comment by zenonVR** [comment]
It's on win10 Pro, memory grows around 1,2 MB before crash. I saw that it happend mostly when I have a project with several controls. When I put the NDI in an empty project it seems to run for a long time, but when I open the NDI in an existing project with list and buttons it crashed very quickly.
The memory is in this case never released and grows up to the crash.
When NDI is alone , the memory goes up and down, so mem release occures in that case.

An other point perhaps linked is that the CPU usage is high, around 40% when Vmix uses only 7% or 10%. As it is running on a virtual machine, does your NDI lib need any video accelerator. 
I did some try on real machine using Vmix and video accelerator Board, but it crashed there also !

I have also build some project sending NDI video to Vmix with the newtek lib, but those takes 2-3% CPU not more.

**Comment by elgarf** [comment]
Ok, I've replaced ndi viewer with media element. You can try it again.

**Comment by zenonVR** [comment]
PB is till the same if controller and Vmix are on the same machine, the CPU goes high and the memory grows more and more up to the crash.
I'll check if the controller is not located on the same machine as the VMIX, perhaps that would help.
I think the Pb is that CPU usage of UTC takes with NDI over 40% as soon as it starts. SO if UTC has only 1 element which is NDI it's running better, but if I have more or less 10-12 widgets in UTC some with lists from about 20 lines , The Pb occur very quickly

**Comment by elgarf** [comment]
Are you creating new External Data or load existing vmc file? Because data provider saves into vmc file, it's not loading from dll every time. So you can move your dll, or delete, or transfer vmc file by email, and there still be data provider.

**Comment by zenonVR** [comment]
no my vmc has no NDI, I create a new UTC with only NDI, th video is playing more or less for 10 mn without pb, never tried more
when I open an existing  vmc with list and button, I add the external dll NDI in this vmc and then it's crashing quickly, so it's not a external provider existing in a vmc but an added NDI.dll in an exsiting vmc

**Comment by elgarf** [comment]
Can you attach new log?

**Comment by zenonVR** [comment]
welcome
[2018-02-13.log](https://github.com/elgarf/vMixUTC/files/1720164/2018-02-13.log)
on machine 3,2 Gb left before running UTC as soon as uc is reaching 1,7 MB it's crashing

**Comment by zenonVR** [comment]
I tried again :
as long as NDI is running alone without doing anything in UTC it's running let say for at least 5 mn,memory is going from 300MB to 600 MB and goes down.
 as soon as I right click in UTC to create a widget, the memory grows , never goes down and UTC do an exception. 
So I guess as soon as UTC has something else to do as only NDI you have a memory leak somewhere and with the amount on video data the memory grows over the reserved 2 GB resources

**Comment by elgarf** [comment]
Are you 100% sure you using latest NDI monitor? 😞
There shouldn't be writeablebitmap anymore.

**Comment by zenonVR** [comment]
Processing.NDI.Lib.x64.dll and x86 are compiled from your project, so 12.02, but vMixUTCNDIMonitorDataProvider.dll is the same one 26.072017, I suppose that this dll is calling the NDI.lib.dll. So perhaps my NDI monitor I downlaod from the Vmix forum is not the good one ;(

**Comment by elgarf** [comment]
Why you don't compile data provider from sources?

**Comment by zenonVR** [comment]
was probably forget from my colleague , let me check this tomorrow

**Comment by elgarf** [comment]
Fixed memory leak in NDILibDotNet2, also fixed aspect correction in the same lib. NDI Monitor now should work better.
