### ISSUE TITLE
Не воспроизводится NDI

### ISSUE THREAD

**Issue by keylase** [elgarf/vMixUTC#5]
При добавлении NDI источника - есть выпадающее меню, но не показывается видео. Не ясно, как диагностировать проблему- тк в логах ничего нет. Все собрано с последнего коммита из исходников. Пробовал и x86 и x64. Пока думаю что некорректно зарегался directshow фильтр, но это не точно, тк нет окна регистрации (оно похоже должно появляться).

**Comment by keylase** [comment]
Действительно - с помощью RadLight Filter Manager нашел что NewTek NDI Source зарегистрирован с битым путём (перемещал проект) - после того, как разрегистрировал (unregistered) - все заработало само собой. Попробую добавить проверку валидности регистрации фильтра и предварительную разрегистрацию если вдруг такая ситуация будет снова.

**Comment by elgarf** [comment]
У меня есть решение в виде кнопочки в статус баре, где можно перезарегистрировать фильтры, но я его ещё не закоммитил.
